version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - prometheus
    environment:
      - PROMETHEUS_URL=http://prometheus:9090

  prometheus:
    image: prom/prometheus:v2.32.1
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090" 

  mongo:
    image: mongo:4.4.10
    ports:
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
  
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword